proposal_expert_task:
  description: >
    Give me a detailed proposal outline about {topic}. The purpose of the proposal is to win business.
  expected_output: >
    A detailed outline with the main topics to cover in a proposal about {topic}. Reference information in {rfp} and address all questions asked.
    Format all sections with a single number followed by a period (ie. "1.", "2.", "3.", etc.) and the section title.
    Include only three sections: Introduction, Plan, and Budget.
    Do not implement any sort of formatting (including numbers (outside of the section title as outlined above), bullet points, section headers, etc.) in the body of the text. It should only be formatted into separate paragraphs and new lines, whenever necessary.
  agent: manager

manager_task:
  description: >
    Conduct a thorough research about {topic}
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains all relevant information.
  expected_output: >
    A detailed {topic} proposal that incorporates knowledge about the industry and proposed solutions. The proposal should cover all sections as previously outlined.
    A fully fledged report with the main topics, each with a full section of information.
    Format all sections with a single number followed by a period (ie. "1.", "2.", "3.", etc.) and the section title.
    Include only three sections: Introduction, Plan, and Budget.
    Do not implement any sort of formatting (including numbers (outside of the section title as outlined above), bullet points, section headers, etc.) in the body of the text. It should only be formatted into separate paragraphs and new lines, whenever necessary.
  agent: manager

analyst_task:
  description: >
    Review the context you got and research proposed solutions that could be implemented for the {topic} proposal.
  expected_output: >
    A detailed summary of the proposed solution ready to be turned into a full-fledged report.
    Format all sections with a single number followed by a period (ie. "1.", "2.", "3.", etc.) and the section title.
    Include only three sections: Introduction, Plan, and Budget.
    Do not implement any sort of formatting (including numbers (outside of the section title as outlined above), bullet points, section headers, etc.) in the body of the text. It should only be formatted into separate paragraphs and new lines, whenever necessary.
  agent: analyst
